### ISSUE TITLE
运行出现找不到zxing.dll错误

### ISSUE THREAD

**Issue by zyxun** [esozh/eso_zh#1]
server 文件夹运行识别英文后，进入翻译阶段后出现找不到zxing2.dll 错误,更换key也没用

**Comment by bssthu** [comment]
可能是我少打包了一些dll文件，我再检查一下

**Comment by bssthu** [comment]
@zyxun  现在应该好了，你再重新下载试试？ (v0.2.2版本)
https://github.com/esozh/eso_zh_server/releases/latest

**Comment by zyxun** [comment]
可以用了，只是有些地方翻译不太准确，例如gather it themselves 翻译成把它自己，我查了百度翻译等工具，都不能准确翻译。非常感谢你的作品了，方便我们很多。

**Comment by zyxun** [comment]
看了许地方，机翻结果准确度较低，我想自己翻译，但怎么显示自己翻译的结果呢？

**Comment by bssthu** [comment]
@zyxun 现在也能翻译书籍的内容，其他的还没想好
目前要显示自己的翻译结果的话，可以修改noun_local.txt，格式是“英文|中文”
不过这游戏的对话数量太多了，不重复的大约有几十万句，感觉官方不出的话基本不可能有人工汉化了。。
